spring:
  application:
    name: generator
  datasource:
    url: jdbc:h2:mem:gdlatte
    driverClassName: org.h2.Driver
    username: gdlatte
    password: 6025
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
